library(rslurm)

source("Sims/sim_utils.R")
source("Sims/section_A_5/sim_worst.R")


METHOD_LEVELS_A5 <- c("Local", "D-subGD", "deLR")


#' Submit the Section A.5 worst-case simulations to Slurm.
#'
#' @param sample_sizes Vector of per-node sample sizes \eqn{n}.
#' @param m Number of nodes.
#' @param repetitions Monte Carlo repetitions for each sample size.
#' @param submit When `TRUE`, dispatch to Slurm; otherwise run locally.
#' @param nodes Number of Slurm nodes to request.
#' @param cpus_per_node Logical CPUs requested per node.
#' @param seed Optional base seed used to derive per-task seeds.
#' @param output_dir Destination directory for artifacts.
#' @param slurm_options Options forwarded to `slurm_apply()`.
#' @param ... Additional arguments forwarded to `sim_worst()`.
#'
#' @return Invisibly returns a list containing the Slurm job, parameters, and
#'   output tables generated by `summarise_slurm_results()`.
run_section_A5_simulations <- function(sample_sizes = c(50, 100, 150, 200, 250, 300),
                                       m = 20,
                                       repetitions = 100,
                                       submit = TRUE,
                                       nodes = length(sample_sizes),
                                       cpus_per_node = 1,
                                       seed = NULL,
                                       output_dir = "Output",
                                       slurm_options = list(),
                                       ...) {
  if (length(sample_sizes) == 0L) {
    stop("sample_sizes must contain at least one value.")
  }
  if (repetitions < 1L) {
    stop("repetitions must be >= 1.")
  }
  if (!is.null(seed) && !is.finite(seed)) {
    stop("seed must be finite when provided.")
  }

  simulation_name <- "section_A_5_worst"
  run_context <- initialize_simulation_run(simulation_name, output_dir = output_dir)

  params <- expand.grid(
    n = sample_sizes,
    batch = seq_len(repetitions),
    KEEP.OUT.ATTRS = FALSE,
    stringsAsFactors = FALSE
  )
  params$N <- params$n * m

  if (!is.null(seed)) {
    seed_offsets <- match(params$n, sample_sizes)
    params$seed <- as.integer(seed) + params$batch + 1000L * seed_offsets
  }

  base_args <- list(
    m = m,
    s = 10,
    p = 100,
    p_flip = 0.05,
    sigma2 = 1,
    rho = 0.1,
    noise_type = "Normal",
    case = 0,
    pc = 0.3,
    T_inner = 500,
    nlambda = 100,
    quiet = TRUE
  )
  override_args <- list(...)
  constant_args <- modifyList(base_args, override_args, keep.null = TRUE)

  sjob <- run_slurm_simulation(
    f = sim_worst,
    params = params,
    jobname = run_context$jobname,
    submit = submit,
    nodes = max(1L, as.integer(nodes)),
    cpus_per_node = max(1L, as.integer(cpus_per_node)),
    global_objects = ls(),
    slurm_options = slurm_options,
    constant_args = constant_args
  )

  if (!submit) {
    rslurm::local_slurm_array(sjob)
    message("Executed locally without submitting to Slurm.")
  } else {
    status <- tryCatch(
      rslurm::get_job_status(sjob)$queue,
      error = function(err) {
        warning("Unable to query Slurm status: ", conditionMessage(err))
        NA_character_
      }
    )
    if (!is.na(status)) {
      message("Current Slurm job status: ", status)
    }
  }

  base::saveRDS(sjob, file.path(run_context$output_dir, paste0(run_context$jobname, ".RDS")))
  base::saveRDS(sjob, file.path(run_context$output_dir, paste0(simulation_name, ".RDS")))

  summary_tables <- summarise_slurm_results(
    sjob = sjob,
    params = params,
    varying_param = "n",
    output_dir = run_context$output_dir,
    jobname = run_context$jobname,
    simulation_name = simulation_name,
    method_levels = METHOD_LEVELS_A5
  )

  slurm_output <- rslurm::get_slurm_out(sjob, outtype = "table", wait = TRUE)
  save(
    list = c("slurm_output", "params", "simulation_name"),
    file = file.path(run_context$output_dir, paste0(run_context$jobname, ".RData"))
  )

  invisible(list(
    job = sjob,
    params = params,
    summary_tables = summary_tables,
    slurm_output = slurm_output,
    run_context = run_context
  ))
}


if (sys.nframe() == 0) {
  run_section_A5_simulations()
}
