// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// deLR
Rcpp::List deLR(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec& betaT, int T_inner, double tau_penalty_factor, int nlambda, double lambda_factor, double lambda_max, bool quiet, double epsilon);
RcppExport SEXP _decentralized1bit_deLR(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP T_innerSEXP, SEXP tau_penalty_factorSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP quietSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< int >::type T_inner(T_innerSEXP);
    Rcpp::traits::input_parameter< double >::type tau_penalty_factor(tau_penalty_factorSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(deLR(X, y, adjacency_matrix, B_init, betaT, T_inner, tau_penalty_factor, nlambda, lambda_factor, lambda_max, quiet, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// deLRwsupp
Rcpp::List deLRwsupp(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec& betaT, int T_inner, double tau_penalty_factor, int nlambda, double lambda_factor, double lambda_max, bool quiet, double epsilon);
RcppExport SEXP _decentralized1bit_deLRwsupp(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP T_innerSEXP, SEXP tau_penalty_factorSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP quietSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< int >::type T_inner(T_innerSEXP);
    Rcpp::traits::input_parameter< double >::type tau_penalty_factor(tau_penalty_factorSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(deLRwsupp(X, y, adjacency_matrix, B_init, betaT, T_inner, tau_penalty_factor, nlambda, lambda_factor, lambda_max, quiet, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// deSubGD_LS_single
Rcpp::List deSubGD_LS_single(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec& betaT, int T, double a, double b, double lambda, double eps, bool quiet);
RcppExport SEXP _decentralized1bit_deSubGD_LS_single(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP TSEXP, SEXP aSEXP, SEXP bSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(deSubGD_LS_single(X, y, adjacency_matrix, B_init, betaT, T, a, b, lambda, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// deSubGD_LS
Rcpp::List deSubGD_LS(arma::mat& X, arma::vec& y, arma::mat& adjacency_matrix, arma::mat& B_init, arma::vec& betaT, int T, double a, double b, int K, int nlambda, double lambda_factor, double lambda_max, double eps, bool quiet);
RcppExport SEXP _decentralized1bit_deSubGD_LS(SEXP XSEXP, SEXP ySEXP, SEXP adjacency_matrixSEXP, SEXP B_initSEXP, SEXP betaTSEXP, SEXP TSEXP, SEXP aSEXP, SEXP bSEXP, SEXP KSEXP, SEXP nlambdaSEXP, SEXP lambda_factorSEXP, SEXP lambda_maxSEXP, SEXP epsSEXP, SEXP quietSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type adjacency_matrix(adjacency_matrixSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type betaT(betaTSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type nlambda(nlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_max(lambda_maxSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type quiet(quietSEXP);
    rcpp_result_gen = Rcpp::wrap(deSubGD_LS(X, y, adjacency_matrix, B_init, betaT, T, a, b, K, nlambda, lambda_factor, lambda_max, eps, quiet));
    return rcpp_result_gen;
END_RCPP
}
// pmax_arma
arma::vec pmax_arma(arma::vec x, double bound);
RcppExport SEXP _decentralized1bit_pmax_arma(SEXP xSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(pmax_arma(x, bound));
    return rcpp_result_gen;
END_RCPP
}
// kernel
arma::mat kernel(arma::mat E, arma::vec h);
RcppExport SEXP _decentralized1bit_kernel(SEXP ESEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type E(ESEXP);
    Rcpp::traits::input_parameter< arma::vec >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel(E, h));
    return rcpp_result_gen;
END_RCPP
}
// mod
double mod(arma::vec v);
RcppExport SEXP _decentralized1bit_mod(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(mod(v));
    return rcpp_result_gen;
END_RCPP
}
// quantile_lossCPP
double quantile_lossCPP(arma::vec x, double tau);
RcppExport SEXP _decentralized1bit_quantile_lossCPP(SEXP xSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile_lossCPP(x, tau));
    return rcpp_result_gen;
END_RCPP
}
// cqr_loss_cpp
double cqr_loss_cpp(arma::mat X, arma::vec y, arma::vec beta, arma::vec alpha, arma::vec& tau);
RcppExport SEXP _decentralized1bit_cqr_loss_cpp(SEXP XSEXP, SEXP ySEXP, SEXP betaSEXP, SEXP alphaSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(cqr_loss_cpp(X, y, beta, alpha, tau));
    return rcpp_result_gen;
END_RCPP
}
// calN_j_cpp
arma::uvec calN_j_cpp(int n, int j);
RcppExport SEXP _decentralized1bit_calN_j_cpp(SEXP nSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(calN_j_cpp(n, j));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_decentralized1bit_deLR", (DL_FUNC) &_decentralized1bit_deLR, 12},
    {"_decentralized1bit_deLRwsupp", (DL_FUNC) &_decentralized1bit_deLRwsupp, 12},
    {"_decentralized1bit_deSubGD_LS_single", (DL_FUNC) &_decentralized1bit_deSubGD_LS_single, 11},
    {"_decentralized1bit_deSubGD_LS", (DL_FUNC) &_decentralized1bit_deSubGD_LS, 14},
    {"_decentralized1bit_pmax_arma", (DL_FUNC) &_decentralized1bit_pmax_arma, 2},
    {"_decentralized1bit_kernel", (DL_FUNC) &_decentralized1bit_kernel, 2},
    {"_decentralized1bit_mod", (DL_FUNC) &_decentralized1bit_mod, 1},
    {"_decentralized1bit_quantile_lossCPP", (DL_FUNC) &_decentralized1bit_quantile_lossCPP, 2},
    {"_decentralized1bit_cqr_loss_cpp", (DL_FUNC) &_decentralized1bit_cqr_loss_cpp, 5},
    {"_decentralized1bit_calN_j_cpp", (DL_FUNC) &_decentralized1bit_calN_j_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_decentralized1bit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
